// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCccF19FzsvTIlYtIUM4wRxPMxeJ6-id4',
    appId: '1:943794666363:web:166b1b5a30058e87615bde',
    messagingSenderId: '943794666363',
    projectId: 'agronova-backend',
    authDomain: 'agronova-backend.firebaseapp.com',
    storageBucket: 'agronova-backend.firebasestorage.app',
    measurementId: 'G-5ZDKYRWBDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdp37qkXgOxLtU7aPHxrkhdf1qPrQ2J44',
    appId: '1:943794666363:android:dba9beacd362f7e5615bde',
    messagingSenderId: '943794666363',
    projectId: 'agronova-backend',
    storageBucket: 'agronova-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjG7NEJ1hBYggF-BpJO_R49Hq30mo5K9g',
    appId: '1:943794666363:ios:824db93d6ad2c424615bde',
    messagingSenderId: '943794666363',
    projectId: 'agronova-backend',
    storageBucket: 'agronova-backend.firebasestorage.app',
    iosBundleId: 'com.example.agronovaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjG7NEJ1hBYggF-BpJO_R49Hq30mo5K9g',
    appId: '1:943794666363:ios:824db93d6ad2c424615bde',
    messagingSenderId: '943794666363',
    projectId: 'agronova-backend',
    storageBucket: 'agronova-backend.firebasestorage.app',
    iosBundleId: 'com.example.agronovaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCccF19FzsvTIlYtIUM4wRxPMxeJ6-id4',
    appId: '1:943794666363:web:ec50659c3104081a615bde',
    messagingSenderId: '943794666363',
    projectId: 'agronova-backend',
    authDomain: 'agronova-backend.firebaseapp.com',
    storageBucket: 'agronova-backend.firebasestorage.app',
    measurementId: 'G-8LBN30BTYN',
  );

}